# Generated by Django 3.0 on 2020-01-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluffyTiget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('rare', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
    ]
