# Generated by Django 3.0 on 2020-01-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_fluffytiget'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FluffyTiget',
            new_name='FluffyTiger',
        ),
    ]
